Closes 1: Update `admiraltemplate` to `admiraldata` and copy from admiral.test
pharmaverse/admiraldata pull request #21
Opened 2023-06-26 22:26 UTC by kaz462

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/devel/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [ ] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [ ] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/devel/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#deprecation)?
- [ ] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [ ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/cran-release/reference/index.html)" page. 
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue in the Development Section on the right hand side.
- [ ] Address all merge conflicts and resolve appropriately 
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

2023-06-26 22:41 UTC, kaz462 commented
Following updates in this PR:
1. Copied `R/data.R`, `dev` and `data` folders from `admiral.test` to `admiraldata` 
```
git clone https://github.com/pharmaverse/admiral.test.git --branch devel --single-branch ./admiral.test --depth 1
cp -R ./admiral.test/data  ./admiraldata
cp -R ./admiral.test/dev  ./admiraldata
cp ./admiral.test/R/data.R  ./admiraldata/R
rm -rf admiral.test
```
2. Updated the following and removed some template files & `tests` folder
> 6. Update/Remove the following files to use your extension name:
>    * `DESCRIPTION` File - Name, Authors
>    * `admiraltemplate.Rproj`
>    * `testthat.R`
>    * `News.md`
* `.Rbuildignore`
3. `devtools::document()` + resolve workflow issues

2023-06-27 13:28 UTC, manciniedoardo requested changes
@kaz462 is it worth **not** copying the data in the `{admiral.test}` data folder and just regenerating it with the files that you copy over? Just to make sure that what you copied over genuinely makes the dataset that you expect?

2023-06-27 14:42 UTC, kaz462 commented on NEWS.md
> + - Many updates across documentation made to match v0.10.0 of `admiral` [PR #51](https://github.com/pharmaverse/admiraldata/pull/51), including:
updated

2023-06-27 14:51 UTC, kaz462 commented
> @kaz462 is it worth **not** copying the data in the `{admiral.test}` data folder and just regenerating it with the files that you copy over? Just to make sure that what you copied over genuinely makes the dataset that you expect?

I got some errors when I try to rerun the programs from `admiral.test/dev`.
@manciniedoardo Should we merge this PR first, and create a separate issue for rerunning datasets (some programs need updates), so that we can work on other issues in parallel?  

e.g., errors from `dev/pp.R`-
```r
> data("pc")
Warning message:
In data("pc") : data set ‘pc’ not found
> 
> # Calculate subjects with all missing;
> blq_usubjid <- pc %>%
+   ungroup() %>%
+   group_by(STUDYID, DOMAIN, USUBJID) %>%
+   summarise(PPORRES = max(PCSTRESN, na.rm = TRUE))
> 
> # Remove from PC, subjects with all blq (placebos);
> remove_usubjid <- blq_usubjid %>% filter(PPORRES == 0)
> 
> pc1 <- anti_join(pc, remove_usubjid, by = c("STUDYID", "DOMAIN", "USUBJID"))
Error in `anti_join()`:
! Join columns in `y` must be present in the data.
✖ Problem with `STUDYID`, `DOMAIN`, and `USUBJID`.
Run `rlang::last_trace()` to see where the error occurred.
```

2023-06-27 18:58 UTC, kaz462 commented
@pharmaverse/admiraldata If you are assigned to `admiraldata` issues, please wait until this PR is merged

2023-06-29 07:33 UTC, manciniedoardo requested changes

2023-06-29 07:33 UTC, manciniedoardo commented on NEWS.md
> +# admiraldata 0.0.2
change to version 0.1.0

2023-06-29 07:33 UTC, manciniedoardo commented on NEWS.md
> +# admiraldata 0.0.1
change to version 0.1.0

2023-06-30 16:53 UTC, kaz462 commented on NEWS.md
> +# admiraldata 0.0.1
Updated

2023-07-04 13:39 UTC, manciniedoardo approved these changes

2023-07-04 13:39 UTC, merged